version: '3.9'

services:
  db:
    image: davidrrf/pokebase:latest
    container_name: db

  api:
    image: davidrrf/pokemon_api:latest
    container_name: api
    depends_on:
      - db

  ui:
    image: davidrrf/pokemon_ui:latest
    container_name: ui
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - ui